-- Observatoire LNR : schéma Supabase
-- À exécuter une fois dans Supabase > SQL Editor > New query > Run.

-- Une ligne par joueur, par saison et par championnat (export Opta).
create table if not exists public.player_seasons (
  id               bigint generated by default as identity primary key,
  championnat      text     not null check (championnat in ('top14', 'prod2')),
  saison           text     not null check (saison ~ '^\d{4}/\d{4}$'),   -- ex. 2025/2026
  joueur           text     not null,
  clubs            text     not null,                                     -- séparés par | si transfert en cours de saison
  minutes          integer  not null default 0,
  matchs           integer  not null default 0,
  titularisations  integer  not null default 0,
  entrees          integer  not null default 0,                           -- apparitions comme remplaçant
  date_naissance   text,                                                  -- AAAA-MM-JJ, vide si inconnue
  postes           text,                                                  -- numéros de poste 1 à 15, séparés par des virgules
  nationalite      text,                                                  -- à compléter
  jiff             text,                                                  -- oui / non, à compléter
  imported_at      timestamptz not null default now()
);

create index if not exists player_seasons_champ_saison_idx
  on public.player_seasons (championnat, saison);

-- Lecture publique, écriture réservée à la clé service (script d'import ou tableau de bord).
alter table public.player_seasons enable row level security;

drop policy if exists "Lecture publique" on public.player_seasons;
create policy "Lecture publique"
  on public.player_seasons
  for select
  to anon, authenticated
  using (true);
